require("classes/paladin/holy/logic/spells/avenging_crusader")
require("classes/paladin/holy/logic/spells/crusader_strike")
require("classes/paladin/holy/logic/spells/hammer_of_wrath")
require("classes/paladin/holy/logic/spells/holy_arnament")
require("classes/paladin/holy/logic/spells/holy_shock")
require("classes/paladin/holy/logic/spells/judgment")
require("classes/paladin/holy/logic/spells/beacon_of_virtue")
