FS.paladin_holy.logic.spells = {}

require("classes/paladin/holy/logic/spells/avenging_crusader")
require("classes/paladin/holy/logic/spells/beacon_of_virtue")
require("classes/paladin/holy/logic/spells/consecration")
require("classes/paladin/holy/logic/spells/crusader_strike") 
require("classes/paladin/holy/logic/spells/divine_toll")
require("classes/paladin/holy/logic/spells/flash_of_light")
require("classes/paladin/holy/logic/spells/hammer_of_wrath")
require("classes/paladin/holy/logic/spells/holy_arnament")
require("classes/paladin/holy/logic/spells/holy_light")
require("classes/paladin/holy/logic/spells/holy_prism")
require("classes/paladin/holy/logic/spells/holy_shock")
require("classes/paladin/holy/logic/spells/judgment")
require("classes/paladin/holy/logic/spells/light_of_dawn")
require("classes/paladin/holy/logic/spells/spend_holy_power")
require("classes/paladin/holy/logic/spells/word_of_glory")
