---@class ModuleConfig
---@field on_update fun() Called on each update cycle
---@field on_fast_update fun() Called on each fast update cycle
---@field on_render fun() Called when rendering the module's visuals
---@field on_render_menu fun() Called when rendering the module's menu
