require("classes/paladin/holy_herald/menu")
require("classes/paladin/holy_herald/settings")
require("classes/paladin/holy_herald/ids/index")
require("classes/paladin/holy_herald/variables")
require("classes/paladin/holy_herald/logic/index")
